module.exports =function(){
   return{

              authors:[
                            {id:1,name:'fazıl',age:25,favoriteBook:'nerdesin aşkım',imgUrl:'1.jpg'},
                            {id:2,name:'Necip',age:25,favoriteBook:'nerdesin aşkım',imgUrl:'2.jpg'},
                            {id:3,name:'Nazım',age:25,favoriteBook:'nerdesin aşkım',imgUrl:'3.jpg'},
                            {id:4,name:'platon',age:25,favoriteBook:'nerdesin aşkım',imgUrl:'4.jpg'},
                            {id:5,name:'stephen',age:25,favoriteBook:'nerdesin aşkım',imgUrl:'5.jpg'},
              ],
                
                 books:[
                            {id:1,name:'soğuk fırtına',authors:'fazıl',catagories:'macera',imgUrl:'1.jpg'},
                            {id:2,name:'karlı dağlar',authors:'fazıl',catagories:'bilim kurgu',imgUrl:'2.jpg'},
                            {id:3,name:'leylim leylim',authors:'fazıl',catagories:'fanstastik',imgUrl:'3.jpg'},
                            {id:4,name:'sen gel',authors:'fazıl',catagories:'şiir',imgUrl:'4.jpg'},
                            {id:5,name:'güzel günler',authors:'fazıl',catagories:'tarih',imgUrl:'5.jpg'},
                            {id:6,name:'heyhat ',authors:'fazıl',catagories:'roman',imgUrl:'6.jpg'},
                            {id:7,name:'taklalı hayat',authors:'fazıl',catagories:'macera',imgUrl:'7.jpg'},
                            {id:8,name:'sıcak fırtına',authors:'fazıl',catagories:'macera',imgUrl:'8.jpg'},
                            {id:9,name:'buz çağı',authors:'fazıl',catagories:'macera',imgUrl:'9.jpg'},
                            {id:10,name:'mersin yolu',authors:'fazıl',catagories:'macera',imgUrl:'10.jpg'},
                            {id:11,name:'tren rayları',authors:'Necip',catagories:'tarih',imgUrl:'11.jpg'},
                            {id:13,name:'akıl sahibi',authors:'Necip',catagories:'tarih',imgUrl:'12.jpg'},
                            {id:14,name:'mesut mucis',authors:'Necip',catagories:'tarih',imgUrl:'13.jpg'},
                            {id:15,name:'laka lukum',authors:'Necip',catagories:'tarih',imgUrl:'14.jpg'},
                            {id:16,name:'ya işte öyle',authors:'Necip',catagories:'fanstastik',imgUrl:'15.jpg'},
                            {id:17,name:'bu kış ',authors:'Necip',catagories:'fanstastik',imgUrl:'16.jpg'},
                            {id:18,name:'son yaz',authors:'Necip',catagories:'fanstastik',imgUrl:'17.jpg'},
                            {id:19,name:'mahluk',authors:'Necip',catagories:'fanstastik',imgUrl:'18.jpg'},
                            {id:20,name:'dağlık',authors:'Necip',catagories:'fanstastik',imgUrl:'19.jpg'},
                            {id:22,name:'salamura',authors:'platon',catagories:'fanstastik',imgUrl:'20.jpg'},
                            {id:23,name:'portakal mevsimi',authors:'platon',catagories:'fanstastik',imgUrl:'21.jpg'},
                            {id:24,name:'yar bakışı',authors:'platon',catagories:'fanstastik',imgUrl:'22.jpg'},
                            {id:25,name:'avsız mevsim',authors:'platon',catagories:'fanstastik',imgUrl:'23.jpg'},
                            {id:26,name:'yayla kuşu',authors:'platon',catagories:'şiir',imgUrl:'24.jpg'},
                            {id:27,name:'raydan hayatlar',authors:'platon',catagories:'şiir',imgUrl:'25.jpg'},
                            {id:28,name:'demir yağmurlar',authors:'platon',catagories:'şiir',imgUrl:'26.jpg'},
                            {id:29,name:'felaket',authors:'platon',catagories:'şiir',imgUrl:'27.jpg'},
                            {id:30,name:'geliyor',authors:'platon',catagories:'şiir',imgUrl:'28.jpg'},
                            {id:31,name:'senin aşık',authors:'Nazım',catagories:'şiir',imgUrl:'29.jpg'},
                            {id:32,name:'mutant',authors:'Nazım',catagories:'şiir',imgUrl:'30.jpg'},
                            {id:33,name:'ne sandın',authors:'Nazım',catagories:'psikolojies',imgUrl:'31.jpg'},
                            {id:34,name:'hakikat',authors:'Nazım',catagories:'psikolojies',imgUrl:'32.jpg'},
                            {id:35,name:'yaz kış',authors:'Nazım',catagories:'psikolojies',imgUrl:'33.jpg'},
                            {id:36,name:'mulkiyet',authors:'Nazım',catagories:'psikolojies',imgUrl:'34.jpg'},
                            {id:37,name:'hakkul',authors:'Nazım',catagories:'psikolojies',imgUrl:'35.jpg'},
                            {id:38,name:'mağrur',authors:'Nazım',catagories:'psikolojies',imgUrl:'36.jpg'},
                            {id:39,name:'neyleyim gülüm',authors:'Nazım',catagories:'psikolojies',imgUrl:'37.jpg'},
                            {id:40,name:'hayat fırtına',authors:'Nazım',catagories:'psikolojies',imgUrl:'38.jpg'},
                            {id:41,name:'acımasız masal',authors:'stephen',catagories:'psikolojies',imgUrl:'39.jpg'},
                            {id:42,name:'yandı yürek',authors:'stephen',catagories:'psikolojies',imgUrl:'40.jpg'},
                            {id:43,name:'imdi yürek',authors:'stephen',catagories:'psikolojies',imgUrl:'41.jpg'},
                            {id:44,name:'yırtulur',authors:'stephen',catagories:'psikolojies',imgUrl:'42.jpg'},
                            {id:45,name:'neyse o',authors:'stephen',catagories:'şiir',imgUrl:'43.jpg'},
                            {id:46,name:'mavi ceket',authors:'stephen',catagories:'şiir',imgUrl:'44.jpg'},
                            {id:47,name:'boşa hayaller',authors:'stephen',catagories:'şiir',imgUrl:'45.jpg'},
                            {id:48,name:'memnun sayfalar',authors:'stephen',catagories:'şiir',imgUrl:'46.jpg'},
                            {id:49,name:'ömür bitti',authors:'stephen',catagories:'şiir',imgUrl:'47.jpg'},
                            {id:50,name:'sabrın sonu selamet',authors:'stephen',catagories:'şiir',imgUrl:'48.jpg'}
              ],
              users:[
                            {id:1,email:'sitkiyildirim100@gmail.com',password:'123456'}
              ]
   }   
}