module.exports =function(){
   return{

              authors:[
                            {id:1,name:'fazıl',age:25,favoriteBook:'nerdesin aşkım',imgUrl:'1.jpg'},
                            {id:2,name:'Necip',age:25,favoriteBook:'nerdesin aşkım',imgUrl:'2.jpg'},
                            {id:3,name:'Nazım',age:25,favoriteBook:'nerdesin aşkım',imgUrl:'3.jpg'},
                            {id:4,name:'platon',age:25,favoriteBook:'nerdesin aşkım',imgUrl:'4.jpg'},
                            {id:5,name:'stephen',age:25,favoriteBook:'nerdesin aşkım',imgUrl:'5.jpg'},
              ],
                
                 books:[
                            {id:1,name:'soğuk fırtına',authors:'fazıl',catagories:'oyna yavrum oyna',imgUrl:'1.jpg'},
                            {id:2,name:'soğuk fırtına',authors:'fazıl',catagories:'oyna yavrum oyna',imgUrl:'2.jpg'},
                            {id:3,name:'soğuk fırtına',authors:'fazıl',catagories:'oyna yavrum oyna',imgUrl:'3.jpg'},
                            {id:4,name:'soğuk fırtına',authors:'fazıl',catagories:'oyna yavrum oyna',imgUrl:'4.jpg'},
                            {id:5,name:'soğuk fırtına',authors:'fazıl',catagories:'oyna yavrum oyna',imgUrl:'5.jpg'},
                            {id:6,name:'soğuk fırtına',authors:'fazıl',catagories:'oyna yavrum oyna',imgUrl:'6.jpg'},
                            {id:7,name:'soğuk fırtına',authors:'fazıl',catagories:'oyna yavrum oyna',imgUrl:'7.jpg'},
                            {id:8,name:'soğuk fırtına',authors:'fazıl',catagories:'oyna yavrum oyna',imgUrl:'8.jpg'},
                            {id:9,name:'soğuk fırtına',authors:'fazıl',catagories:'oyna yavrum oyna',imgUrl:'9.jpg'},
                            {id:10,name:'soğuk fırtına',authors:'fazıl',catagories:'oyna yavrum oyna',imgUrl:'10.jpg'},
                            {id:11,name:'soğuk fırtına',authors:'Necip',catagories:'oyna yavrum oyna',imgUrl:'11.jpg'},
                            {id:13,name:'soğuk fırtına',authors:'Necip',catagories:'oyna yavrum oyna',imgUrl:'12.jpg'},
                            {id:14,name:'soğuk fırtına',authors:'Necip',catagories:'oyna yavrum oyna',imgUrl:'13.jpg'},
                            {id:15,name:'soğuk fırtına',authors:'Necip',catagories:'oyna yavrum oyna',imgUrl:'14.jpg'},
                            {id:16,name:'soğuk fırtına',authors:'Necip',catagories:'oyna yavrum oyna',imgUrl:'15.jpg'},
                            {id:17,name:'soğuk fırtına',authors:'Necip',catagories:'oyna yavrum oyna',imgUrl:'16.jpg'},
                            {id:18,name:'soğuk fırtına',authors:'Necip',catagories:'oyna yavrum oyna',imgUrl:'17.jpg'},
                            {id:19,name:'soğuk fırtına',authors:'Necip',catagories:'oyna yavrum oyna',imgUrl:'18.jpg'},
                            {id:20,name:'soğuk fırtına',authors:'Necip',catagories:'oyna yavrum oyna',imgUrl:'19.jpg'},
                            {id:22,name:'soğuk fırtına',authors:'platon',catagories:'oyna yavrum oyna',imgUrl:'20.jpg'},
                            {id:23,name:'soğuk fırtına',authors:'platon',catagories:'oyna yavrum oyna',imgUrl:'21.jpg'},
                            {id:24,name:'soğuk fırtına',authors:'platon',catagories:'oyna yavrum oyna',imgUrl:'22.jpg'},
                            {id:25,name:'soğuk fırtına',authors:'platon',catagories:'oyna yavrum oyna',imgUrl:'23.jpg'},
                            {id:26,name:'soğuk fırtına',authors:'platon',catagories:'oyna yavrum oyna',imgUrl:'24.jpg'},
                            {id:27,name:'soğuk fırtına',authors:'platon',catagories:'oyna yavrum oyna',imgUrl:'25.jpg'},
                            {id:28,name:'soğuk fırtına',authors:'platon',catagories:'oyna yavrum oyna',imgUrl:'26.jpg'},
                            {id:29,name:'soğuk fırtına',authors:'platon',catagories:'oyna yavrum oyna',imgUrl:'27.jpg'},
                            {id:30,name:'soğuk fırtına',authors:'platon',catagories:'oyna yavrum oyna',imgUrl:'28.jpg'},
                            {id:31,name:'soğuk fırtına',authors:'Nazım',catagories:'oyna yavrum oyna',imgUrl:'29.jpg'},
                            {id:32,name:'soğuk fırtına',authors:'Nazım',catagories:'oyna yavrum oyna',imgUrl:'30.jpg'},
                            {id:33,name:'soğuk fırtına',authors:'Nazım',catagories:'oyna yavrum oyna',imgUrl:'31.jpg'},
                            {id:34,name:'soğuk fırtına',authors:'Nazım',catagories:'oyna yavrum oyna',imgUrl:'32.jpg'},
                            {id:35,name:'soğuk fırtına',authors:'Nazım',catagories:'oyna yavrum oyna',imgUrl:'33.jpg'},
                            {id:36,name:'soğuk fırtına',authors:'Nazım',catagories:'oyna yavrum oyna',imgUrl:'34.jpg'},
                            {id:37,name:'soğuk fırtına',authors:'Nazım',catagories:'oyna yavrum oyna',imgUrl:'35.jpg'},
                            {id:38,name:'soğuk fırtına',authors:'Nazım',catagories:'oyna yavrum oyna',imgUrl:'36.jpg'},
                            {id:39,name:'soğuk fırtına',authors:'Nazım',catagories:'oyna yavrum oyna',imgUrl:'37.jpg'},
                            {id:40,name:'soğuk fırtına',authors:'Nazım',catagories:'oyna yavrum oyna',imgUrl:'38.jpg'},
                            {id:41,name:'soğuk fırtına',authors:'stephen',catagories:'oyna yavrum oyna',imgUrl:'39.jpg'},
                            {id:42,name:'soğuk fırtına',authors:'stephen',catagories:'oyna yavrum oyna',imgUrl:'40.jpg'},
                            {id:43,name:'soğuk fırtına',authors:'stephen',catagories:'oyna yavrum oyna',imgUrl:'41.jpg'},
                            {id:44,name:'soğuk fırtına',authors:'stephen',catagories:'oyna yavrum oyna',imgUrl:'42.jpg'},
                            {id:45,name:'soğuk fırtına',authors:'stephen',catagories:'oyna yavrum oyna',imgUrl:'43.jpg'},
                            {id:46,name:'soğuk fırtına',authors:'stephen',catagories:'oyna yavrum oyna',imgUrl:'44.jpg'},
                            {id:47,name:'soğuk fırtına',authors:'stephen',catagories:'oyna yavrum oyna',imgUrl:'45.jpg'},
                            {id:48,name:'soğuk fırtına',authors:'stephen',catagories:'oyna yavrum oyna',imgUrl:'46.jpg'},
                            {id:49,name:'soğuk fırtına',authors:'stephen',catagories:'oyna yavrum oyna',imgUrl:'47.jpg'},
                            {id:50,name:'soğuk fırtına',authors:'stephen',catagories:'oyna yavrum oyna',imgUrl:'48.jpg'}
              ],
              users:[
                            {id:1,email:'sitkiyildirim100@gmail.com',password:'123456'}
              ]
   }   
}